baseURL = 'https://r2axz.me/'
languageCode = 'ru-ru'
title = 'Заметки радиолюбителя'
theme = 'hugo-theme-stack'

defaultContentLanguage = 'ru'

titleCaseStyle = 'none'

[params]
  mainSections = ["post"]
  favicon = 'favicon/favicon.ico'

[params.dateFormat]
  published = '02 January 2006'

[params.sidebar.avatar]
  enabled = true
  local = true
  src = 'imgs/avatar.jpg'

[params.article]
  math = true

[markup.goldmark.extensions.passthrough]
  enable = true
[markup.goldmark.extensions.passthrough.delimiters]
  block = [['\[', '\]'], ['$$', '$$']]
  inline = [['\(', '\)']]

[params.colorScheme]
  toggle = false
  default = 'light'

[[params.widgets.homepage]]
  type = 'search'

[[params.widgets.homepage]]
  type = 'tag-cloud'

[[params.widgets.homepage]]
  type = 'archives'

[menus]

  [[menus.main]]
  identifier = "home"
  name = "Главная страница"
  url = "/"
  weight = 10
  [menus.main.params]
  icon = "home"

  [[menus.main]]
  identifier = "search"
  name = "Поиск"
  url = "/page/search/"
  weight = 20
  [menus.main.params]
  icon = "search"
  newtab = true

  [[menus.main]]
  identifier = "archives"
  name = "Архивы"
  url = "/page/archives/"
  weight = 30
  [menus.main.params]
  icon = "archives"
