baseURL = 'https://r2axz.me/'
languageCode = 'ru-ru'
title = 'Заметки радиолюбителя'
theme = 'hugo-theme-stack'

defaultContentLanguage = 'ru'

titleCaseStyle = 'none'

[params]
  mainSections = ["post"]
  favicon = 'favicon/favicon.ico'

[params.dateFormat]
  published = '01 January 2006'

[params.sidebar.avatar]
  enabled = true
  local = true
  src = 'imgs/avatar.jpg'

[params.article]
  math = true

[markup.goldmark.extensions.passthrough]
  enable = true
[markup.goldmark.extensions.passthrough.delimiters]
  block = [['\[', '\]'], ['$$', '$$']]
  inline = [['\(', '\)']]

[params.colorScheme]
  toggle = false
  default = 'light'
